{{
    fivetran_utils.union_data(
        table_identifier='account', 
        database_variable='xero_database', 
        schema_variable='xero_schema', 
        default_database=target.database,
        default_schema='xero',
        default_variable='account'
    )
}} 