name: 'ga4'
version: '6.0.1'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

profile: 'ga4'

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  ga4_incremental_strategy: "{% if target.type == 'bigquery' %}insert_overwrite{% elif target.type == 'snowflake' %}delete+insert{% endif %}"

models:
  ga4:
    +materialized: view
    marts:
      +materialized: table
