name: 'ga4'
version: '0.1'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


#vars:
#    start_date: "20210120" # Defines the earliest GA4 _TABLE_SUFFIX to load into base events model. 
#    project: "bigquery-public-data"
#    dataset: "ga4_obfuscated_sample_ecommerce"
#    include_intraday_events: true|false # indicates whether intraday events should be unioned into the event model
#    page_view_custom_parameters:
#      - name: my_custom_param
#        value_type: string_value

# custom parameters are registered by creating a var matching the event name where the custom parameter occurs
# and providing the name, matching the parameters name
# and matching the value_type to the type of column in BigQuery (string_value, int_value, float_value, double_value)
# the below example shows a page_view enhanced with the clean_event event parameter from the ga4_obfuscated_sample_ecommerce project
#    page_view:
#      - name: "clean_event"
#        value_type: "string_value"  

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  ga4:
    +materialized: view
    marts:
      +materialized: table
