name: 'ga4'
version: '6.1.0'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

profile: 'bq_ga4'

vars:
  start_date: "20230306" # Defines the earliest GA4 _TABLE_SUFFIX to load into base events model.
  source_project: "analytics"
  property_ids: [id]
  frequency: "daily"
  conversion_events: ['add_to_cart', 'large_button_clicked']
  static_incremental_days: 3
  derived_session_properties:
    - event_parameter: "ga_session_id"
      session_property_name: "ga_session_id"
      value_type: "int_value"
    - event_parameter: "page_title"
      session_property_name: "page_title"
      value_type: "string_value"
  derived_user_properties:
    - event_parameter: "page_title"
      user_property_name: "page_title"
      value_type: "string_value"

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ga4:
    +materialized: view
    marts:
      +materialized: table
