name: 'ga4'
version: '6.1.0'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

profile: 'default'

vars:
  source_project: "{{ env_var('BIGQUERY_PROJECT') }}"
  property_ids: ["{{ env_var('BIGQUERY_PROPERTY_ID') }}"]
  start_date: "20230306"
  static_incremental_days: 3
  derived_session_properties:
    - event_parameter: "page_location"
      session_property_name: "most_recent_page_location"
      value_type: "string_value"
  derived_user_properties:
    - event_parameter: "page_title"
      user_property_name: "most_recent_page_title"
      value_type: "string_value"
  conversion_events: ['large_button_clicked', 'add_to_cart']
  session_attribution_lookback_window_days: 30

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ga4:
    +materialized: view
    marts:
      +materialized: table
