name: 'ga4'
version: '3.2.1'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ga4:
    +materialized: view
    marts:
      +materialized: table
vars:
  ga4:
    project: "ga4-export-381215"
    dataset: "analytics_286597709"
    start_date: "20230319" # Earliest date to load
    frequency: "daily" # daily|streaming|daily+streaming. See 'Export Frequency' below. 
    query_parameter_exclusions: ["gclid","fbclid","_ga"] 
    default_custom_parameters:
      - name: "new_sro_ui"
        value_type: "string_value"
        conversion_events:['purchase','download']
conversion_events:['add_to_cart','generate_lead','purchase','purchase_gift_voucher']