"""
SQL syntax validation tests for combine_property_data macros using sqlglot.

These tests verify that the SQL generated by the multi-site cloning macros
is syntactically valid BigQuery SQL. They run without requiring a BigQuery
connection, making them fast and suitable for CI/CD.
"""

import pytest

sqlglot = pytest.importorskip("sqlglot", reason="sqlglot required for SQL syntax validation tests")


class TestGenerateCloneStatementSyntax:
    """Test that generate_clone_statement produces valid BigQuery SQL."""

    @pytest.mark.parametrize(
        "source_project,source_schema,source_table,dest_project,dest_schema,dest_table",
        [
            # Standard daily table
            (
                "my-source-project",
                "analytics_123456789",
                "events_20240101",
                "my-target-project",
                "combined_data",
                "events_20240101123456789",
            ),
            # Intraday table
            (
                "my-source-project",
                "analytics_123456789",
                "events_intraday_20240102",
                "my-target-project",
                "combined_data",
                "events_intraday_20240102123456789",
            ),
            # Different property ID
            (
                "my-source-project",
                "analytics_987654321",
                "events_20240103",
                "my-target-project",
                "combined_data",
                "events_20240103987654321",
            ),
            # Project names with numbers
            (
                "project-123",
                "analytics_111222333",
                "events_20240101",
                "project-456",
                "ga4_combined",
                "events_20240101111222333",
            ),
            # Underscores in project names
            (
                "my_source_project",
                "analytics_123456789",
                "events_20240101",
                "my_target_project",
                "combined_dataset",
                "events_20240101123456789",
            ),
        ],
    )
    def test_clone_statement_parses(
        self,
        source_project,
        source_schema,
        source_table,
        dest_project,
        dest_schema,
        dest_table,
    ):
        """Verify clone statement SQL parses as valid BigQuery."""
        # This matches the output of generate_clone_statement macro
        sql = f"CREATE OR REPLACE TABLE `{dest_project}.{dest_schema}.{dest_table}` CLONE `{source_project}.{source_schema}.{source_table}`;"

        # sqlglot should parse this without raising an exception
        parsed = sqlglot.parse(sql, read="bigquery")

        assert len(parsed) == 1, f"Expected 1 statement, got {len(parsed)}"
        assert parsed[0] is not None, "Parsed statement should not be None"


class TestGenerateDropStatementSyntax:
    """Test that generate_drop_statement produces valid BigQuery SQL."""

    @pytest.mark.parametrize(
        "project,schema,table",
        [
            # Standard intraday table cleanup
            ("my-target-project", "combined_data", "events_intraday_20240101123456789"),
            ("my-target-project", "combined_data", "events_intraday_20240102987654321"),
            # Different project/schema combinations
            ("project-123", "ga4_combined", "events_intraday_20240101111222333"),
            ("my_project", "my_dataset", "events_intraday_20240101123456789"),
        ],
    )
    def test_drop_statement_parses(self, project, schema, table):
        """Verify drop statement SQL parses as valid BigQuery."""
        # This matches the output of generate_drop_statement macro
        sql = f"DROP TABLE IF EXISTS `{project}.{schema}.{table}`;"

        # sqlglot should parse this without raising an exception
        parsed = sqlglot.parse(sql, read="bigquery")

        assert len(parsed) == 1, f"Expected 1 statement, got {len(parsed)}"
        assert parsed[0] is not None, "Parsed statement should not be None"


class TestGenerateCreateSchemaStatementSyntax:
    """Test that generate_create_schema_statement produces valid BigQuery SQL."""

    @pytest.mark.parametrize(
        "project,schema",
        [
            ("my-target-project", "combined_data"),
            ("another-project", "ga4_combined"),
            ("project-123", "dataset_456"),
            ("my_project", "my_dataset"),
        ],
    )
    def test_create_schema_statement_parses(self, project, schema):
        """Verify create schema statement SQL parses as valid BigQuery."""
        # This matches the output of generate_create_schema_statement macro
        sql = f"CREATE SCHEMA IF NOT EXISTS `{project}.{schema}`;"

        # sqlglot should parse this without raising an exception
        parsed = sqlglot.parse(sql, read="bigquery")

        assert len(parsed) == 1, f"Expected 1 statement, got {len(parsed)}"
        assert parsed[0] is not None, "Parsed statement should not be None"


class TestCombinedStatementsSyntax:
    """Test that a batch of statements (as generated by combine_property_data) parses."""

    def test_full_clone_batch_parses(self):
        """
        Verify that a realistic batch of statements parses correctly.

        This simulates what combine_property_data generates: a create schema
        statement followed by multiple clone and drop statements.
        """
        sql = """
        CREATE SCHEMA IF NOT EXISTS `my-target-project.combined_data`;
        CREATE OR REPLACE TABLE `my-target-project.combined_data.events_20240101123456789` CLONE `my-source-project.analytics_123456789.events_20240101`;
        DROP TABLE IF EXISTS `my-target-project.combined_data.events_intraday_20240101123456789`;
        CREATE OR REPLACE TABLE `my-target-project.combined_data.events_intraday_20240102123456789` CLONE `my-source-project.analytics_123456789.events_intraday_20240102`;
        CREATE OR REPLACE TABLE `my-target-project.combined_data.events_20240101987654321` CLONE `my-source-project.analytics_987654321.events_20240101`;
        DROP TABLE IF EXISTS `my-target-project.combined_data.events_intraday_20240101987654321`;
        """

        # sqlglot should parse all statements
        parsed = sqlglot.parse(sql, read="bigquery")

        # Should have 6 statements
        assert len(parsed) == 6, f"Expected 6 statements, got {len(parsed)}"
        for i, stmt in enumerate(parsed):
            assert stmt is not None, f"Statement {i} should not be None"
